### ISSUE TITLE
Add session control, so that when user refresh they don't get locked out from dashboard 

### ISSUE THREAD

**Issue by angelicalin** [visdesignlab/Sanguine#103]
we could have an endpoint api/whoami  that returns 200 if logged in and 401 if not. That would be an easy way to check with the backend if the user is logged in

**Comment by JackWilb** [comment]
Can we close this @angelicalin or do we need to preserve the session by using the state?

**Comment by angelicalin** [comment]
I just want to keep this, and close it when I finish with ReactRouter stuff.
