### ISSUE TITLE
Add patient outcomes to the filters

### ISSUE THREAD

**Issue by JackWilb** [visdesignlab/Sanguine#13]
Readmission
Kidney Failure
Ventilator minutes
Length of Stay
Death

**Comment by angelicalin** [comment]
Kidney failure and drugs usage related to blood management would be a next step to add.

**Comment by angelicalin** [comment]
I put in the performance timestamp on the risk score and outcome, each query takes about 1 second to complete. Since I request each aggregated attribute then calculate the total risk score/outcome, the whole thing would take a long time (11 seconds when there are 11 surgeons as aggregated attribute.)

**Comment by JackWilb** [comment]
@angelicalin Does the query not accept a list of patients? You have to do them one at a time?

**Comment by angelicalin** [comment]
I do input a list of patients. But it is seperated by aggregated attributes, e.g. surgeons
I guess I could just input everything in there and put each patient in the corrected aggregated attribute bin from the query result, however, we might have an issue with length of the input exceed 1000

**Comment by JackWilb** [comment]
Make pat_ids not required for the risk_score and patient_outcomes endpoints to speed up the query performance.

**Comment by JackWilb** [comment]
Just a couple pieces left, check the TODOs on #99

**Comment by JackWilb** [comment]
And some of the outcomes should only be checked intra/extra op. Send a list to Ryan to see which should go where

**Comment by JackWilb** [comment]
Tranexaminc acid and Amicar: would care most about these given either before or during surgery.

Iron and B12 would be before surgery

anticoagulants and antiplatelet drugs: want to know if they were used before surgery and (ideally) whether they were stopped in advance of the surgery (so the patient isn't unnecessarily prone to bleeding)
