### ISSUE TITLE
test the changed role W/R access

### ISSUE THREAD

**Issue by haihan-lin** [visdesignlab/Sanguine#174]
We haven't tested the W/R access change will actually change the access.

Will test on the next UI change.

**Comment by haihan-lin** [comment]
@JackWilb Is this still an open issue that we need to address for the next PR?

**Comment by JackWilb** [comment]
> @JackWilb Is this still an open issue that we need to address for the next PR?

Yes, I think we still need to test this

**Comment by JackWilb** [comment]
Tested and it's work, opened #183, #184 for the lingering/newly found issues
