### ISSUE TITLE
Antifibrinolytics (Amicar) - Missing Data

### ISSUE THREAD

**Issue by ryanmetcalf** [visdesignlab/Sanguine#283]
We appear to be missing Amicar administrations since the vast majority of cases did not get Amicar according to this visualization
<img width="1094" alt="Screenshot 2024-08-12 at 4 06 57 PM" src="https://github.com/user-attachments/assets/6d8736d4-0c23-4e9d-a303-f91789e6cc96">

**Comment by JackWilb** [comment]
This has been fixed with the data warehouse team
