### ISSUE TITLE
Add a way to filter by any variable

### ISSUE THREAD

**Issue by JackWilb** [visdesignlab/Sanguine#77]
For example filter by drg weight with brushing. Might use lineup and might require us extracting the lineup filtering component into something we can mount

**Comment by angelicalin** [comment]
**Stuff that we already have charts/queries on:

Categorical:**

Year
surgeon ID
anesthesiologists ID
Mortality

**Numerical**: 

APR_DRG_WEIGHT
Transfused units
Ventilator minutes

**Some other filters that Ryan mentioned would be useful ( and we currently don’t have):**
# of tubes of blood drawn during the admission (In the lab values table, unique container IDs should each indicate one tube of blood.)

Temperature (if <36C, it’s harder for blood to clot)
pH (if below normal, it’s harder for blood to clot)
Creatinine level (this is a lab value that indicates kidney dysfunction if elevated)

A drug called dideoxyarginine vasopressin (or DDAVP): this relates to creatinine above. When creatinine is high, platelets do not work to stop bleeding. DDAVP helps the platelets work in this situation.
Other important drugs: prothrombin complex concentrate (trade name is Kcentra), recombinant factor VIIa, vitamin K.

preexisting comorbidities (diabetes, hypertension, renal failure, endocarditis, smoker, liver disease), body mass index (BMI), 

received Amicar or tranexamic acid before or during surgery.
